### PR TITLE
Update Readme.md with Headless mode and clearer instructions

### PR DESCRIPTION
**Pull request by olokos**
Hey, great work on the script! Really useful, especially now 😄 

I noticed you've said it's not possible to run it headless in readme, which isn't true. 
We can do it with `slimerjs --headless` and it will run the script without opening 2 windows, one being slimerjs and another actual firefox steam.

It's especially crucial for those with slow PCs/Heavy loaded PCs who want to use it 24/7.
This will also help to ease the use of resources by quite a bit in general.

Good work though, I couldn't find any trustworthy tool and yours works wonders! ❤️ 

I have tested headless mode for 1 hour and it runs perfectly fine, but I leave the decision to make everybody use headless mode up to you, here I added it to FAQ.

### CODE REVIEW

**Comment by Sleepydragn1** [comment]
I actually have been aware of SlimerJS' headless mode for a while, but since headless mode doesn't properly render the stream, it's not useful for this particular script.

... at least, that's what I wanted to say, but having actually tested it, no, you're entirely correct, it works fine. Not that you need any proof, but here's a screenshot taken via SlimerJS' page rendering function showing it rendering the stream as one would expect: 

Suck on this, previous me

Which is weird, since I distinctly remember converting this project early on from being PhantomJS based to SlimerJS based due to having issues with PhantomJS being headless. At some point along the way, I must've picked up some misconceptions about how headless browsers actually work.

Either way, thank you for bringing this up, and thank you for taking the time to write up a pull request. It's always nice to have my misconceptions corrected, and it's gratifying to see others care about the projects I make enough to try to improve them.

Going forward, I'm going to close this pull request, and simply change the README to recommend it as the default option for running the script, along with fixing the FAQ and adding a section explaining what it does. I'll also change the wording of "profile name" to "SlimerJS profile name" as recommended by your commits, as that seems like a solid suggestion.

**Comment by olokos** [comment]
@Sleepdragn1
Cheers man, I appreciate your work, took me a few hours to set it up and figure out all this stuff, including this write up, but I got what I wanted from twitch drop. 
I also have this nifty bit of software for the future now.
Whenever I see work like this, underappreciated, that is an instant sign for me to contribute! ❤️

Having that said, could you please ammend your commit and properly mention me using @olokos ?
It's not much, but makes it so much better looking for me 😊

Thank you!

**Comment by Sleepydragn1** [comment]
@olokos
Sorry about that, I actually forgot that you could tag a username like that. Unfortunately, I think changing a commit that's already pushed to master would be a bad idea, especially since there's at least one person that has a fork that includes that commit already.

Would tagging you properly on the next commit that I make suffice?

**Comment by olokos** [comment]
I should've mentioned you could do `git commit --amend` but now there are more commits
so it's not that simple.
If you want to take a moment, you can do it like this
https://stackoverflow.com/questions/1186535/how-to-modify-a-specified-commit

But sure, you can just mention the Readme.md commit and tag @olokos next to it kinda like:
`Thanks to @olokos for 053016c157f681009a4c162824e1e17aa0d404c7 `
I'm fine with both, so choose one you are most comfortable with 😄

**Pull request closed without merging**
